/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.*;
import java.util.ArrayList;

/**
 *
 * @author Macarena
 */
public class Principal extends javax.swing.JFrame {
    
    public static ArrayList<Huesped> huespedes = new ArrayList();
    public static ArrayList<Habitacion> habitaciones = new ArrayList();
    public static ArrayList<TipoHabitacion> tipoHabitaciones = new ArrayList();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemFormularioHuespedes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemFormularioHabitaciones = new javax.swing.JMenuItem();
        MenuItemFormularioTipoHabitaciones = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemNuevaReserva = new javax.swing.JMenuItem();
        jMenuItemBuscarReserva = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
        );

        jMenu1.setText("Huespedes");

        MenuItemFormularioHuespedes.setText("Formulario Huespedes");
        MenuItemFormularioHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFormularioHuespedesActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemFormularioHuespedes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Habitaciones");

        MenuItemFormularioHabitaciones.setText("Formulario Habitaciones");
        MenuItemFormularioHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFormularioHabitacionesActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemFormularioHabitaciones);

        jMenuBar1.add(jMenu2);

        MenuItemFormularioTipoHabitaciones.setText("Tipos de Habitaciones");

        jMenuItem1.setText("Formulario Tipo de Habitaciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuItemFormularioTipoHabitaciones.add(jMenuItem1);

        jMenuBar1.add(MenuItemFormularioTipoHabitaciones);

        jMenu3.setText("Reservas");

        jMenuItemNuevaReserva.setText("Nueva Reserva");
        jMenuItemNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaReservaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemNuevaReserva);

        jMenuItemBuscarReserva.setText("Buscar/Borrar Reserva");
        jMenuItemBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarReservaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemBuscarReserva);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Salir");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void MenuItemFormularioHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFormularioHuespedesActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaHuesped vistaHuesped = new VistaHuesped(huespedes);
        vistaHuesped.setVisible(true);
        escritorio.add(vistaHuesped);
        escritorio.moveToFront(vistaHuesped);
        escritorio.repaint();
        
        
    }//GEN-LAST:event_MenuItemFormularioHuespedesActionPerformed

    private void MenuItemFormularioHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFormularioHabitacionesActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaHabitaciones vistaHabitaciones = new VistaHabitaciones(habitaciones);
        vistaHabitaciones.setVisible(true);
        escritorio.add(vistaHabitaciones);
        escritorio.moveToFront(vistaHabitaciones);
        escritorio.repaint();
        
    }//GEN-LAST:event_MenuItemFormularioHabitacionesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaTipoHabitacion vistaTipoHabitacion = new VistaTipoHabitacion(tipoHabitaciones);
        vistaTipoHabitacion.setVisible(true);
        escritorio.add(vistaTipoHabitacion);
        escritorio.moveToFront(vistaTipoHabitacion);
        escritorio.repaint();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaReservaActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaReservas vistaReservas = new VistaReservas();
        vistaReservas.setVisible(true);
        escritorio.add(vistaReservas);
        escritorio.moveToFront(vistaReservas);
        escritorio.repaint();
        
    }//GEN-LAST:event_jMenuItemNuevaReservaActionPerformed

    private void jMenuItemBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarReservaActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaBuscarReservas vistaBuscarReservas = new VistaBuscarReservas();
        vistaBuscarReservas.setVisible(true);
        escritorio.add(vistaBuscarReservas);
        escritorio.moveToFront(vistaBuscarReservas);
        escritorio.repaint();
        
    }//GEN-LAST:event_jMenuItemBuscarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemFormularioHabitaciones;
    private javax.swing.JMenuItem MenuItemFormularioHuespedes;
    private javax.swing.JMenu MenuItemFormularioTipoHabitaciones;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemBuscarReserva;
    private javax.swing.JMenuItem jMenuItemNuevaReserva;
    // End of variables declaration//GEN-END:variables
}
